// <auto-generated />
using CafeteriaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeteriaApp.Data.Migrations
{
    [DbContext(typeof(CafeteriaAppContext))]
    [Migration("20250504200207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CafeteriaApp.Models.Cafe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadStock")
                        .HasColumnType("int");

                    b.Property<bool>("EsComercioJusto")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NumeroCompras")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("Variedad")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cafes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadStock = 4,
                            EsComercioJusto = true,
                            NumeroCompras = 3,
                            Precio = 1.1m,
                            Tipo = "Café solo",
                            Variedad = "Nigeria"
                        },
                        new
                        {
                            Id = 2,
                            CantidadStock = 4,
                            EsComercioJusto = true,
                            NumeroCompras = 3,
                            Precio = 1.0m,
                            Tipo = "Café solo",
                            Variedad = "Brasil"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
