// <auto-generated />
using System;
using CafeteriaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeteriaApp.Data.Migrations
{
    [DbContext(typeof(CafeteriaAppContext))]
    partial class CafeteriaAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CafeteriaApp.Models.Cafe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadStock")
                        .HasColumnType("int");

                    b.Property<bool>("EsComercioJusto")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NumeroCompras")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("Variedad")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cafes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadStock = 4,
                            EsComercioJusto = true,
                            NumeroCompras = 3,
                            Precio = 1.1m,
                            Tipo = "Café solo",
                            Variedad = "Nigeria"
                        },
                        new
                        {
                            Id = 2,
                            CantidadStock = 4,
                            EsComercioJusto = true,
                            NumeroCompras = 3,
                            Precio = 1.0m,
                            Tipo = "Café solo",
                            Variedad = "Brasil"
                        });
                });

            modelBuilder.Entity("CafeteriaApp.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ClienteSatisfecho")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("CafeteriaApp.Models.PedidoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CafeId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CafeId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoDetalles");
                });

            modelBuilder.Entity("CafeteriaApp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("SaltContrasena")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Correo = "admin@gmail.com",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HashContrasena = "DA6E5F37539A6CC32BC1A519D08B4A5BB012E23A47EB002CF719F081ABC9B463A8FB15728D7E103AB9AA94445B92E794B4C2456EDE79432C9DD508A6856471AF",
                            Rol = "admin",
                            SaltContrasena = new byte[] { 6, 180, 134, 209, 96, 88, 60, 119, 131, 1, 148, 163, 178, 90, 20, 2, 253, 27, 72, 117, 232, 26, 82, 226, 24, 202, 90, 213, 186, 179, 115, 11, 146, 58, 113, 9, 175, 64, 246, 158, 80, 54, 220, 113, 17, 23, 44, 229, 51, 202, 58, 238, 49, 222, 254, 218, 217, 202, 8, 144, 186, 1, 25, 143 }
                        });
                });

            modelBuilder.Entity("CafeteriaApp.Models.Pedido", b =>
                {
                    b.HasOne("CafeteriaApp.Models.Usuario", "Usuario")
                        .WithMany("HistoricoPedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CafeteriaApp.Models.PedidoDetalle", b =>
                {
                    b.HasOne("CafeteriaApp.Models.Cafe", "Cafe")
                        .WithMany()
                        .HasForeignKey("CafeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeteriaApp.Models.Pedido", "Pedido")
                        .WithMany("PedidoDetalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cafe");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("CafeteriaApp.Models.Pedido", b =>
                {
                    b.Navigation("PedidoDetalles");
                });

            modelBuilder.Entity("CafeteriaApp.Models.Usuario", b =>
                {
                    b.Navigation("HistoricoPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
